server:
  port: 9009
spring:
  application:
    name: tensquare‐sms #指定服务名
  rabbitmq:
    host: 192.168.179.129
aliyun:
  sms:
    accessKeyId: you guess
    accessKeySecret: you guess
    template_code: you guess
    sign_name: you guess
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
