server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
jwt:
  config:
    key: itcast
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
