server:
  port: 9006
spring:
  application:
    name: tensquare-spit #指定服务名
  data:
    mongodb:
      host: 192.168.179.129
      database: spitdb
  redis:
    host: 192.168.179.129
    password: sUlnkfBOQ3MglYN1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
